baseURL: "https://souzarodri.github.io/test/" 
title: rodrigo de souza
theme: PaperMod
enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20
taxonomies:
    tag: tags
menu:
    main:
        - name: reportagens
          url: reportagens/
          weight: 2 
        - name: assessoria de imprensa
          url: assessoria/
          weight: 3
        - name: produção de conteúdo
          url: conteudo/
          weight: 4
        - name: substack
          url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
          weight: 5
params:
    description: "jornalismo *reportagem *assessoria *conteúdo"
    author: rodrigo de souza
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: rodrigo de souza
          subtitle: "jornalista formado pela escola de comunicação da ufrj (eco/ufrj), com publicações em o dia, o globo e uol. atualmente na secretaria municipal de saúde do rio de janeiro. direitos humanos, saúde, cidadania, cultura e administração pública. jornalismo investigativo, jornalismo de dados e outros jornalismos."
          imageUrl: "perfil.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: reportagens
              url: reportagens/
            - name: assessoria de imprensa
              url: assessoria/
            - name: produção de conteúdo
              url: conteudo/
            - name: Blog
              url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
    socialIcons:
        - name: Email
          url: mailto:rod.azes@gmail.com  # Substitua pelo seu email
        - name: LinkedIn
          url: https://linkedin.com/in/desouzarod  # Substitua pelo seu perfil
        - name: Instagram
          url: https://instagram.com/rod.azes  # Substitua pelo seu perfil
    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "rodrigo de souza"
      icon: favicon.ico
      iconHeight: 18
markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
